eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8882

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ghuan/Spring-Cloud
          searchPaths: configrepertory
  application:
    name: config-server